name: Test workflow

on:
  push:
    branches:
      - ass_b

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        architecture: x64
        check-latest: false
        server-id: github
        server-username: GITHUB_ACTOR
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true
        job-status: success

    - name: Build and test
      run: |
        mvn clean install -DskipTests -pl jest-common -am
        mvn -pl jest-common -Dtest=io.searchbox.indices.RolloverTest#testBasicUriGeneration
        mvn -pl jest-common edu.illinois:nondex-maven-plugin:2.1.1:nondex -DnondexRuns=10 -Dtest=io.searchbox.indices.RolloverTest#testBasicUriGeneration

